# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Install build dependencies
RUN apt-get update && apt-get install -y gcc libffi-dev build-essential && rm -rf /var/lib/apt/lists/*

# Upgrade pip
RUN pip install --upgrade pip

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml ./
COPY README.md ./
COPY swagger.json ./
COPY src ./src
COPY LICENSE ./

# Install hatchling
RUN pip install hatchling

# Build and install the package
RUN pip install .

# Expose port if needed (MCP over stdio does not require ports, but if switching to SSE, might be needed)

# Default command to run the MCP server
CMD ["rootly-mcp-server", "--transport", "stdio"]
