name: Test Matrix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv (Unix)
      if: runner.os != 'Windows'
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install uv (Windows)
      if: runner.os == 'Windows'
      run: |
        irm https://astral.sh/uv/install.ps1 | iex
        echo "$env:USERPROFILE\.local\bin" >> $env:GITHUB_PATH

    - name: Install dependencies (Unix)
      if: runner.os != 'Windows'
      run: |
        uv pip install --system -e .
        uv pip install --system pytest pytest-cov

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        uv pip install --system -e .
        uv pip install --system pytest pytest-cov

    - name: Run tests
      run: |
        pytest tests/ -v --tb=short

    - name: Display test summary
      if: always()
      run: |
        echo "Tests completed on ${{ matrix.os }} with Python ${{ matrix.python-version }}"